In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import yaml

In [4]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [10]:
df_cc = pd.read_csv(config["input_data"]["file1"])
df_cc

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

In [11]:
df_cc.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   year                        1200 non-null   int64
 1   country                     1200 non-null   str
 2   global_avg_temperature      1200 non-null   float64
 3   temperature_anomaly         1200 non-null   float64
 4   max_temperature             1200 non-null   float64
 5   min_temperature             1200 non-null   float64
 6   co2_concentration_ppm       1200 non-null   float64
 7   annual_rainfall_mm          1200 non-null   float64
 8   sea_level_rise_mm           1200 non-null   float64
 9   sea_surface_temperature     1200 non-null   float64
 10  heatwave_days               1200 non-null   int64
 11  drought_index               1200 non-null   float64
 12  flood_events_count          1200 non-null   int64
 13  forest_cover_percent        1200 non-null   float64
 14  deforestation_rate          1200 non-null   float64
 15  fossil_fuel_consumption     1200 non-null   float64
 16  renewable_energy_share      1200 non-null   float64
 17  air_quality_index           1200 non-null   int64
 18  predicted_temperature_2050  1200 non-null   float64
 19  climate_risk_index          1200 non-null   float64
dtypes: float64(15), int64(4), str(1)
memory usage: 187.6 KB

In [15]:
def clean_cc(df_cc):
    #drop columns
    df_cc = df_cc.drop(['global_avg_temperature', 'temperature_anomaly', 'max_temperature','min_temperature', 'drought_index'], axis=1)
    return df_cc
df_cc = clean_cc(df_cc)
display(df_cc)

,year,country,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,387.85,814.11,2.14,14.38,50,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,407.24,735.61,4.19,15.33,37,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,450.54,1982.92,6.46,15.90,27,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,415.42,1162.01,3.37,17.26,25,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,403.42,1170.25,4.64,16.62,41,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,409.92,1483.91,4.72,17.81,44,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,420.29,777.83,4.97,16.96,54,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,464.19,251.69,2.13,15.99,5,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,407.62,1343.91,2.10,15.19,41,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,445.16,914.09,2.77,14.54,9,12,66.56,0.48,62.18,7.55,102,1.64,88.74

In [17]:
df_cc['country'].unique()

<StringArray>
[  'Germany',     'India',  'Pakistan',       'USA', 'Australia',    'France',
    'Canada',     'China',    'Brazil',        'UK']
Length: 10, dtype: str

In [16]:
#sort by country and year
df_sorted = df_cc.sort_values(by=['country', 'year'], ascending=[True, True])

# Display the sorted DataFrame
display(df_sorted)

,year,country,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
495,1980,Australia,408.61,372.44,3.74,15.55,58,7,43.72,0.54,59.71,52.69,79,2.31,71.61
720,1980,Australia,433.33,1083.79,3.96,14.68,10,5,43.71,3.17,62.21,30.59,43,2.76,76.76
955,1980,Australia,409.03,1239.98,2.64,14.88,16,4,48.55,1.94,28.23,19.45,41,1.91,53.13
17,1981,Australia,414.47,488.33,3.27,18.75,41,11,29.24,2.80,60.22,54.92,112,2.82,40.87
22,1981,Australia,459.18,731.00,3.02,14.73,37,7,43.19,3.00,72.88,34.06,138,1.96,44.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2024,USA,409.44,1226.02,2.60,13.41,44,3,41.84,3.46,43.24,24.91,87,1.19,75.12
520,2024,USA,380.46,1044.71,4.57,19.15,57,9,16.53,0.81,79.90,56.34,187,2.28,72.75
838,2024,USA,417.69,1214.90,3.31,16.07,56,4,22.86,1.96,56.87,47.38,106,2.30,62.72
740,2025,USA,454.73,793.41,3.15,16.26,40,14,54.41,1.20,60.08,54.73,145,2.31,21.62
866,2025,USA,442.96,1032.52,4.91,15.14,36,5,32.12,3.05,42.57,53.23,65,2.54,16.09

In [ ]:
#see all values of columns
pd.set_option('display.max_rows', None)
# Reset option to default if needed
#pd.reset_option('display.max_rows')

In [8]:
df.to_csv(config[])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1246852126.py, line 1)